POST http://127.0.0.1:5000/api/users/login
content-type: application/json

{
    "email":"admin@example.com",
    "password":"123456"
}
###########################################
GET http://127.0.0.1:5000/api/users/profile
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmVjZDRiMDhiYjAyMmRjY2MzMmQ2MCIsImlhdCI6MTY2NDAxMjU4MCwiZXhwIjoxNjY2NjA0NTgwfQ.5vdqkE9LG6a8xXMMDEL4sVEKM7DCtQXZCUAnTsmm4ck

{
    
}

###########################################
POST http://127.0.0.1:5000/api/users/register
content-type: application/json

{
    "name":"HuynhLoc",
    "email":"huynhloc@example.com",
    "password":"123456"
}

###########################################
PUT http://127.0.0.1:5000/api/users/updateProfile
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmVjZDRiMDhiYjAyMmRjY2MzMmQ2MCIsImlhdCI6MTY2NDAxMjU4MCwiZXhwIjoxNjY2NjA0NTgwfQ.5vdqkE9LG6a8xXMMDEL4sVEKM7DCtQXZCUAnTsmm4ck

{
    "name":"HuynhLoc057",
    "email":"huynhloc577@example.com"
}